# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 use_frameworks!
target 'NetmeraAppSwiftSDK' do
  # Comment the next line if you don't want to use dynamic frameworks
 
pod "NetmeraAnalytic"
pod "NetmeraAnalyticAutotracking"
pod "NetmeraNotification"
pod "NetmeraAdvertisingId"
pod "NetmeraLocation"
pod "NetmeraGeofence"
pod "NetmeraNotificationInbox"

 
  # Pods for NetmeraAppSwiftSDK

end

target 'MyNetmeraServiceExtension' do
  pod "NetmeraNotificationServiceExtension"
end


post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = "YES"
  
  
  
    installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |variant, xcconfig|
        xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
          xcconfig_path = config.base_configuration_reference.real_path
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
        end
      end
  end

 end
  end
  
